import 'package:flutter/material.dart';

import '../../core/constants/app_images.dart';
import '../../core/theme/app_colors.dart';
import 'home_models.dart';

// ── Hero Slides ────────────────────────────────────────────────────────────────
const List<HeroSlide> kHeroSlides = [
  HeroSlide(
    title: 'Book a Pandit\nfrom ₹499',
    subtitle: 'Experienced pandits for all puja ceremonies',
    icon: Icons.auto_awesome,
    imagePath: 'assets/images/image1.jpg',
    gradient: [Color(0xFFD4611A), Color(0xFFBF9B30)],
    actionLabel: 'Book Now',
    actionRoute: '/booking',
  ),
  HeroSlide(
    title: 'Online Jyotish\nConsultation',
    subtitle: 'Talk to certified astrologers 24/7',
    icon: Icons.stars_rounded,
    imagePath: 'assets/images/image2.jpg',
    gradient: [Color(0xFF2D4A8A), Color(0xFF4A6FBE)],
    actionLabel: 'Consult Now',
    actionRoute: '/consultation',
  ),
  HeroSlide(
    title: 'Vastu Shastra\nExpert Advice',
    subtitle: 'Harmonise your home and workspace',
    icon: Icons.home_work_rounded,
    imagePath: 'assets/images/image3.jpg',
    gradient: [Color(0xFF7C1E3C), Color(0xFFBF5070)],
    actionLabel: 'Learn More',
    actionRoute: '/packages',
  ),
  HeroSlide(
    title: 'Sacred Shop\nPuja Samagri',
    subtitle: 'Authentic ritual items delivered home',
    icon: Icons.shopping_bag_rounded,
    imagePath: 'assets/images/image4.jpg',
    gradient: [Color(0xFF5B2D8A), Color(0xFFA052D4)],
    actionLabel: 'Shop Now',
    actionRoute: '/shop',
  ),
];

// ── Categories ────────────────────────────────────────────────────────────────
const List<CategoryItem> kCategories = [
  CategoryItem(
    label: 'Puja',
    icon: Icons.auto_awesome,
    color: Color(0xFFFF6B35),
    route: '/services',
  ),
  CategoryItem(
    label: 'Astrology',
    icon: Icons.stars_rounded,
    color: Color(0xFF2D4A8A),
    route: '/consultation',
  ),
  CategoryItem(
    label: 'Vastu',
    icon: Icons.home_work_rounded,
    color: Color(0xFF1B5E20),
    route: '/services',
  ),
  CategoryItem(
    label: 'Packages',
    icon: Icons.folder_special_rounded,
    color: Color(0xFF6A1B9A),
    route: '/packages',
  ),
  CategoryItem(
    label: 'Shop',
    icon: Icons.store_rounded,
    color: Color(0xFFBF6000),
    route: '/shop',
  ),
];

// ── Mock Pandits ──────────────────────────────────────────────────────────────
const List<MockPandit> kMockPandits = [
  MockPandit(
    id: 'p1',
    name: 'Pt. Ramesh Sharma',
    speciality: 'Vedic Astrology',
    rating: 4.9,
    reviewCount: 312,
    experience: 18,
    isOnline: true,
    avatarInitials: 'RS',
    avatarColor: Color(0xFFFF6B35),
    imagePath: AppImages.pandit1,
  ),
  MockPandit(
    id: 'p2',
    name: 'Acharya Sunil Joshi',
    speciality: 'Vastu & Griha Puja',
    rating: 4.7,
    reviewCount: 185,
    experience: 12,
    isOnline: true,
    avatarInitials: 'SJ',
    avatarColor: Color(0xFF2D4A8A),
    imagePath: AppImages.pandit2,
  ),
  MockPandit(
    id: 'p3',
    name: 'Pt. Kavita Mishra',
    speciality: 'Navgraha & Katha',
    rating: 4.8,
    reviewCount: 240,
    experience: 15,
    isOnline: false,
    avatarInitials: 'KM',
    avatarColor: Color(0xFF6A1B9A),
    imagePath: AppImages.pandit3,
  ),
  MockPandit(
    id: 'p4',
    name: 'Swami Prakash Das',
    speciality: 'Havan & Yajna',
    rating: 5.0,
    reviewCount: 98,
    experience: 22,
    isOnline: true,
    avatarInitials: 'PD',
    avatarColor: Color(0xFF1B5E20),
    imagePath: AppImages.pandit1,
  ),
  MockPandit(
    id: 'p5',
    name: 'Pt. Ashok Trivedi',
    speciality: 'Kundali & Remedies',
    rating: 4.6,
    reviewCount: 410,
    experience: 20,
    isOnline: false,
    avatarInitials: 'AT',
    avatarColor: Color(0xFFBF6000),
    imagePath: AppImages.pandit2,
  ),
];

// ── Mock Packages ─────────────────────────────────────────────────────────────
final List<MockPackage> kMockPackages = [
  MockPackage(
    id: 'pkg1',
    title: 'Satyanarayan Puja',
    description: 'Complete puja with all samagri, experienced pandit on-site',
    price: 1499,
    durationMinutes: 90,
    isOnline: false,
    categoryIcon: Icons.auto_awesome,
    badgeLabel: 'Best Seller',
    badgeColor: AppColors.success,
    isPopular: true,
  ),
  MockPackage(
    id: 'pkg2',
    title: 'Kundali Analysis',
    description: '60-min detailed birth chart reading via video call',
    price: 799,
    durationMinutes: 60,
    isOnline: true,
    categoryIcon: Icons.stars_rounded,
    badgeLabel: 'Online',
    badgeColor: AppColors.info,
    isPopular: true,
  ),
  MockPackage(
    id: 'pkg3',
    title: 'Vastu Home Visit',
    description: 'On-site vastu inspection for 2-3 BHK with report',
    price: 2499,
    durationMinutes: 120,
    isOnline: false,
    categoryIcon: Icons.home_work_rounded,
    badgeLabel: 'Premium',
    badgeColor: AppColors.warning,
  ),
  MockPackage(
    id: 'pkg4',
    title: 'Navgraha Havan',
    description: 'All 9 planet appeasement havan with prasad delivery',
    price: 3499,
    durationMinutes: 180,
    isOnline: false,
    categoryIcon: Icons.brightness_5_rounded,
    badgeLabel: 'Most Booked',
    badgeColor: AppColors.primary,
    isPopular: true,
  ),
  MockPackage(
    id: 'pkg5',
    title: 'Daily Horoscope Chat',
    description: 'Weekly chat consultation + daily written predictions',
    price: 299,
    durationMinutes: 30,
    isOnline: true,
    categoryIcon: Icons.chat_rounded,
    badgeLabel: 'Budget',
    badgeColor: const Color(0xFF6A1B9A),
  ),
];
